---
taps:
  - homebrew/cask
 
packages:
  - { name: ansible, state: present }
  - { name: anyenv, state: present }
  - { name: awscli, state: present }
  - { name: bat, state: present }
  - { name: bdw-gc, state: present }
  - { name: berkeley-db, state: present }
  - { name: brotli, state: present }
  - { name: bzip2, state: present }
  - { name: c-ares, state: present }
  - { name: ca-certificates, state: present }
  - { name: cask, state: present }
  - { name: coreutils, state: present }
  - { name: curl, state: present }
  - { name: direnv, state: present }
  - { name: docker, state: present }
  - { name: emacs, state: present }
  - { name: exa, state: present }
  - { name: fzf, state: present }
  - { name: gdbm, state: present }
  - { name: gettext, state: present }
  - { name: git, state: present }
  - { name: git-secrets, state: present }
  - { name: glib, state: present }
  - { name: gmp, state: present }
  - { name: gnu-sed, state: present }
  - { name: gnutls, state: present }
  - { name: grep, state: present }
  - { name: guile, state: present }
  - { name: htop, state: present }
  - { name: icu4c, state: present }
  - { name: isl, state: present }
  - { name: jansson, state: present }
  - { name: jemalloc, state: present }
  - { name: libev, state: present }
  - { name: libevent, state: present }
  - { name: libffi, state: present }
  - { name: libgcrypt, state: present }
  - { name: libgpg-error, state: present }
  - { name: libidn2, state: present }
  - { name: libmaxminddb, state: present }
  - { name: libmetalink, state: present }
  - { name: libmpc, state: present }
  - { name: libnghttp2, state: present }
  - { name: libsmi, state: present }
  - { name: libssh, state: present }
  - { name: libssh2, state: present }
  - { name: libtasn1, state: present }
  - { name: libtool, state: present }
  - { name: libunistring, state: present }
  - { name: libyaml, state: present }
  - { name: lua, state: present }
  - { name: lz4, state: present }
  - { name: m4, state: present }
  - { name: mas, state: present }
  - { name: monolith, state: present }
  - { name: mpdecimal, state: present }
  - { name: mpfr, state: present }
  - { name: mysql, state: present }
  - { name: ncurses, state: present }
  - { name: neofetch, state: present }
  - { name: nettle, state: present }
  - { name: nghttp2, state: present }
  - { name: nginx, state: present }
  - { name: openldap, state: present }
  - { name: openssl@1.1, state: present }
  - { name: p11-kit, state: present }
  - { name: pcre, state: present }
  - { name: pcre2, state: present }
  - { name: perl, state: present }
  - { name: pkg-config, state: present }
  - { name: protobuf, state: present }
  - { name: python@3.10, state: present }
  - { name: python@3.9, state: present }
  - { name: readline, state: present }
  - { name: rtmpdump, state: present }
  - { name: ruby, state: present }
  - { name: screen, state: present }
  - { name: screenfetch, state: present }
  - { name: screenresolution, state: present }
  - { name: six, state: present }
  - { name: socat, state: present }
  - { name: sqlite, state: present }
  - { name: starship, state: present }
  - { name: tcl-tk, state: present }
  - { name: telnet, state: present }
  - { name: terminal-notifier, state: present }
  - { name: tig, state: present }
  - { name: tmux, state: present }
  - { name: tree, state: present }
  - { name: unbound, state: present }
  - { name: utf8proc, state: present }
  - { name: vim, state: present }
  - { name: wget, state: present }
  - { name: xz, state: present }
  - { name: zlib, state: present }
  - { name: zsh, state: present }
  - { name: zsh-completions, state: present }
  - { name: zstd, state: present }