#
# git
#
- name: create git symlink
  become: no
  file:
    src: ~/dotfiles/git/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .gitconfig
    - .gitignore_global

#
# tmux
#
- name: create tmux symlink
  become: no
  file:
    src: ~/dotfiles/tmux/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .tmux
    - .tmux.conf

#
# vim
#

# - name: create vim symlink
#   become: no
#   file:
#     src: ~/dotfiles/vim/{{ item }}
#     dest: ~/{{ item }}
#     state: link
#     force: yes
#   with_items:
#     - .vim
#     - .vimrc

#
# vim
#

- name: create nvim symlink
  become: no
  file:
    src: ~/dotfiles/neovim/{{ item }}
    dest: ~/.config/nvim/{{ item }}
    state: link
    force: yes
  with_items:
    - init.vim

#
# zsh
#
- name: create zsh symlink
  become: no
  file:
    src: ~/dotfiles/zsh/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .zaliases
    - .zprofile
    - .zshrc

#
# starship
#
- name: check config dir
  stat:
    path: ~/.config
  register: config

- name: create config dir
  become: no
  file:
    path: ~/.config
    state: directory
    owner: yuta
    group: staff
    mode: 0755
  when: not config.stat.exists

- name: create starship symlink
  become: no
  file:
    src: ~/dotfiles/starship/{{ item }}
    dest: ~/.config/{{ item }}
    state: link
    force: yes
  with_items:
    - starship.toml

#
# virtualbox
#
- name: create virtualbox symlink
  become: no
  file:
    src: ~/dotfiles/virtualbox/{{ item }}
    dest: /etc/vbox/{{ item }}
    state: link
    force: yes
  with_items:
    - networks.conf

#
# vscode
#
- name: create vscode symlink
  become: no
  file:
    src: ~/dotfiles/vscode/{{ item }}
    dest: ~/Library/Application Support/Code/User/{{ item }}
    state: link
    force: yes
  with_items:
    - settings.json
    - keybindings.json

#
# homebrew
#
- name: create homebrew symlink
  become: no
  file:
    src: ~/dotfiles/homebrew/{{ item }}
    dest: ~/Library/LaunchAgents/{{ item }}
    state: link
    force: yes
  with_items:
    - localhost.homebrew-autoupdate.plist
