name: Ubuntu

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run deploy.sh
        run: ./deploy.sh -s
        working-directory: ./etc/scripts

  source-bashrc-on-ubunutu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: curl -fsSL https://starship.rs/install.sh | sh /dev/stdin -f
      - name: Setup
        run: |
          sudo apt-get install curl git
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.11.3
      - name: Run source .bashrc
        run: |
          bash .bashrc
          bash .bash_profile
          bash .bash_aliases
        working-directory: ./bash/ubuntu
