name: Ubuntu

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run deploy.sh
        run: ./deploy.sh -s
        working-directory: ./etc/scripts

  source-bashrc-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
      - name: Run source .bashrc
        run: |
          bash .bashrc
          bash .bash_profile
          bash .bash_aliases
        working-directory: ./bash/ubuntu
