name: linux CI

on:
  push:
    branches:
      - main
      - 'feature/**'
    # paths:
    #   - .github/workflows/linux.yml
  pull_request:
    branches:
      - main

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Error Check
    - name: Run deploy.sh
      # run: ${GITHUB_WORKSPACE}/etc/scripts/deploy.sh
      run: ls -la
