name: linux CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  ubuntu-deploy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run deploy.sh
        run: ./deploy.sh
        working-directory: ./etc/scripts
      - name: Run deploy.sh
        run: pwd
