name: OSX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-on-OSX-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run deploy.sh
        run: ./deploy.sh
        working-directory: ./etc/scripts

  install-on-OSX-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run install.sh
        # run: ./install.sh
        run: pwd
        working-directory: ./etc/scripts
