name: OSX CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  OSX-test:
    runs-on: macos-latest
    steps:
      - name: Run deploy.sh
        uses: actions/checkout@v2
        run: ${GITHUB_WORKSPACE}/etc/scripts/deploy.sh
