name: OSX

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  deploy-on-OSX-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run deploy.sh
        run: ./deploy.sh
        working-directory: ./etc/scripts

  defaults-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run defaults.sh
        run: ./defaults.sh
        working-directory: ./etc/scripts
