name: OSX

on:
  push:
    paths:
    - 'config/**'
  pull_request:
    paths:
    - 'config/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-on-OSX-x64:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run deploy.sh
      run: ./deploy.sh -s
      working-directory: ./etc/scripts

  brew-bundle-on-OSX-x64:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run brew bundle
      run: brew bundle
      working-directory: ./config/homebrew/x64

  source-zshrc-on-OSX-x64:
    runs-on: macos-latest
    env:
      HOME: /Users/runner/work/dotfiles
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      run: |
        brew update
        brew install zsh
        brew install zsh-completions
        brew install zsh-autosuggestions
        brew install starship
        brew tap shellspec/shellspec
        brew install shellspec

    - name: Run source zshrc files
      run: |
        zsh .zshrc
        zsh .zprofile
        zsh .zaliases
      working-directory: ./config/zsh/x64

    - name: Run ShellSpec
      run: |
        shellspec
      working-directory: ./


          # brew update
          # brew install zsh
          # zsh autoload -U compinit
  # shellspec-on-OSX-x64:
  #   runs-on: macos-latest
  #   env:
  #     HOME: /Users/runner/work/dotfiles
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run shellspec
  #       run: |
  #         brew update
  #         brew cleanup
  #         brew tap shellspec/shellspec
  #         brew install shellspec
  #         shellspec
