name: OSX

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  deploy-on-OSX-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run deploy.sh
        run: ./deploy.sh -s
        working-directory: ./etc/scripts

  defaults-on-OSX-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run defaults.sh
        run: ./defaults.sh
        working-directory: ./etc/scripts

  source-zshrc-on-OSX-x64:
    runs-on: macos-latest
    env:
      HOME: /Users/runner/work/dotfiles
    steps:
      - uses: actions/checkout@v2
      - name: Run source .zshrc
        run: |
          zsh .zshrc
        working-directory: ./zsh/x64

          # brew update
          # brew install zsh
  # shellspec-on-OSX-x64:
  #   runs-on: macos-latest
  #   env:
  #     HOME: /Users/runner/work/dotfiles
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run shellspec
  #       run: |
  #         brew update
  #         brew cleanup
  #         brew tap shellspec/shellspec
  #         brew install shellspec
  #         shellspec
