name: OSX CI

on:
  push:
    branches:
      - main
      - 'feature/**'
    # paths:
    #   - .github/workflows/osx.yml
  pull_request:
    branches:
      - main

jobs:
  OSX-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run rmlink.sh
        run: ./rmlink.sh
        working-directory: etc/scripts/mklink
        env:
          DOT_DIRECTORY: /Users/runner/work/dotfiles/dotfiles

      - name: Run mklink_x64.sh
        run: ./mklink_x64.sh
        working-directory: etc/scripts/mklink
        env:
          DOT_DIRECTORY: /Users/runner/work/dotfiles/dotfiles
          MKLINK_SCRIPT_DIR: /Users/runner/work/dotfiles/dotfiles/etc/scripts/mklink


      - name: Run mklink_arm64.sh
        run: ./mklink_arm64.sh
        working-directory: etc/scripts/mklink
        env:
          DOT_DIRECTORY: /Users/runner/work/dotfiles/dotfiles
          MKLINK_SCRIPT_DIR: /Users/runner/work/dotfiles/dotfiles/etc/scripts/mklink

      - name: Run deploy.sh
        run: ./deploy.sh
        working-directory: etc/scripts
