name: OSX CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  OSX-test:
    runs-on: macos-latest
    env:
      MKLINK_SCRIPT_DIR: ${GITHUB_WORKSPACE}/etc/scripts/mklink
    steps:
      - uses: actions/checkout@v2

      - name: Run rmlink.sh
        # run: ${GITHUB_WORKSPACE}/etc/scripts/mklink/rmlink.sh
        run: ${{MKLINK_SCRIPT_DIR}}/rmlink.sh
        # run: pwd


      - name: Run confirm
        run: ls -la ${GITHUB_WORKSPACE}/etc/scripts

      - name: Run deploy.sh
        # uses: actions/checkout@v2
        # run: ${GITHUB_WORKSPACE}/etc/scripts/deploy.sh
        run: ./deploy.sh
        working-directory: etc/scripts
